name: WakaTime Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours UTC
  workflow_dispatch:       # Manual trigger via GitHub UI

jobs:
  update-readme:
    name: Update WakaTime stats in README
    runs-on: ubuntu-latest

    steps:
      - name: Use athul/waka-readme action
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
